# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

project = "pix.xcodeproj"
workspace = "pix.xcworkspace"

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
      app_identifier: "com.maximenory.pix",
      readonly: true
    )
    increment_build_number(xcodeproj: project)
    build_app(
      workspace: workspace,
      scheme: "pix",
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight
  end
end
